###################################################################################################

- name: firewall | install

  apt: name=ufw state=present

  become: true

###################################################################################################

- name: firewall | add rules

  ufw: rule={{ item.rule  }}
       port={{ item.port  }}
      proto={{ item.proto }}

  with_items:
    
    '{{ firewall_rules }}'

  become: true

###################################################################################################

- name: firewall | enable

  ufw: state=enabled 
      policy={{ firewall_global_rule }}

  become: true

###################################################################################################
