###################################################################################################

- name: uptime | get

  shell: uptime -p | cut -f 1 -d ' ' --complement

  register: uptime

###################################################################################################

- name: uptime | display

  debug: msg='Server is up less than a 1 minute'

  when: uptime.stdout|trim == ''

###################################################################################################

- name: uptime | display

  debug: msg='Server is up {{ uptime.stdout }}'

  when: uptime.stdout|trim != ''

###################################################################################################

